-- Add GENERATED BY DEFAULT AS IDENTITY to id columns.
--
-- The id columns were plain bigint NOT NULL with no auto-generation.
-- PostgREST upserts (INSERT ... ON CONFLICT) send NULL for unspecified columns,
-- which violates NOT NULL when there's no default/identity.
-- GENERATED BY DEFAULT creates an auto-incrementing sequence and allows
-- PostgREST merge-duplicates upserts to work correctly.
--
-- Applied via Supabase Management API on 2026-03-01.

ALTER TABLE deepstack_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART 190000);
ALTER TABLE deepstack_fills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART 1000);
ALTER TABLE deepstack_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART 1);
